[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "esp32cam-backend"
version = "0.1.0"
dependencies = []

[tool.setuptools.packages.find]
include = ["backend*"]
